.\" Manpage de kongslave.
.\" Contactarse con pablogiudice(at)gmail.com para consultas o errores 
.TH man 8 "feb 9 2016" "1.0" "kongslave man page"

.SH NAME
kongslave \- Simple opendnp3 slave simulator

.SH SYNOPSIS
KongSlaveTest  tcpserver 0.0.0.0 14641 10 101 100

.SH DESCRIPTION
TBD

.SH OPTIONS
TBD

.SH COMANDOS
TBD

.IP "h"
Shows the help menu with some commands.



.SH BUGS
No tiene bugs conocidos.
.SH AUTOR
Pablo Giudice (pablogiudice@gmail.com)
